version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sis_barber_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barbersis123
      POSTGRES_DB: sis_barber
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: